### ISSUE TITLE
Too many BUGS for PLAYing

### ISSUE THREAD

**Issue by amber-rose** [Hugobros3/chunkstories#7]
Game is not fun becase there many bugs! Is bugs a feature??

**Comment by Hugobros3** [comment]
It's pretty obvious you are a troll, and indeed your toxic behavior and negging attempts already got you banned on the Discord server. As all trolls goes, you are a coward and created a fake account just so you could spam my projects with insulting PRs.

This is honestly pretty pathetic and I wish you had better things to do with your life than spending it trying to piss other people off.

**Comment by amber-rose** [comment]
Why did u NOT fix this ISSUE you CANNOT avoid the TASK of WRITING tests?
